version: '3.1'
services:
  casdoor:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c 'doppler run -- ./server --createDatabase=true'
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - RUNNING_IN_DOCKER="true"
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    volumes:
      - ./conf:/conf/
  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - casdoor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  casdoor-db:
    driver: local